### ISSUE TITLE
<Contents>どのアニメにするかを考えてください。

### ISSUE THREAD

**Issue by s1f10210356** [s1f10210356/team-project#13]
URLを決めるためにどのアニメにするかを決めてください。
- とりあえず被らないようにまずは系統をここのコメント欄に入力お願いします。
- アニメを日曜日までに決めてください。
お願いしますm(__)m

**Comment by s1F10210413** [comment]
異世界系で「ノーゲーム・ノーライフ」を考えてます。
作品は変えるかもそれないですが問題がなければ異世界系で行こうと思ってます。

**Comment by s1f10210356** [comment]
ネットゲーム異世界系？
SAO

**Comment by s1F10210413** [comment]
変更
青春系：「月がきれい」

**Comment by S1F102100490** [comment]
バトル系：僕のヒーローアカデミア

**Comment by s1f10210356** [comment]
みんなありがとうございますm(__)m
これで締めます
