### ISSUE TITLE
<HTML>home page のコンテンツ部分の型を三つ作成して下さい。

### ISSUE THREAD

**Issue by s1f10210356** [s1f10210356/team-project#2]
PPTを参考にしながら増幅することも考慮した書き方をしてください。
[https://iniad-lectures.slack.com/files/U01SY5NQAK0/F024P3X7F45/____________web__________________.pptx](url)

P.sコンテンツ部分とは日常系とかバトル系とか書かれている部分です。

**Comment by S1F102100490** [comment]
もっと何か加えたほうがいいですかね？

**Comment by s1f10210356** [comment]
https://github.com/s1f10210356/team-project/commit/c03efb1392f53ae6ed2b503e74c16af278ea30bf#commitcomment-52360547
これらをお願いしますm(__)m
