### ISSUE TITLE
<CONTENTS>緊急でアニメのコンテンツ作成をお願いしますm(__)m

### ISSUE THREAD

**Issue by s1f10210356** [s1f10210356/team-project#36]
訂正して割り振ったいくつかのアニメのコンテンツを考えて挿入お願いしますm(__)m

**Comment by s1f10210356** [comment]
index
青春系(月が奇麗　色づく世界の明日から：森君　かぐやさまは告らせたい：しゆう君）
戦闘系・バトル（ヒーローアカデミア　追加ブラッククローバー：しゆう君　呪術廻戦：しゆう君）
SF系（ソードアートオンライン　オーバーロード：森君　七星のスバル：森）
日常系・ほのぼの（ゆるキャン：しゆう君　working!!:森君　？森君）
異世界アニメ（転スラ・森君　盾の勇者：しゆう君　ノーゲームノーライフ：森君）
恋愛アニメ（俺の青春ラブコメは間違っている：森君　さくら荘のペットな彼女：森君　凪のあすから：森君）
ギャグアニメ（さいくすおの災難：しゆう君　這いよれニャル子さん：森君　荒川アンダーザブリッジ：吉田）
訂正：オーバーロード：森君　俺の青春ラブコメは間違っている：森君　さくら荘のペットな彼女：森君　転スラ・森君

**Comment by s1F10210413** [comment]
作業開始のコメントを忘れてました。
作業は完了しました。

**Comment by s1f10210356** [comment]
了解しました
ありがとうございますm(__)m
